# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "1":{
      x: 136,
      y: 57,
      yaw: 90},
    "2":{
      x: 138,
      y: 57,
      yaw: 90},
    "3":{
      x: 140,
      y: 57,
      yaw: 90},
    "4":{
      x: 142,
      y: 57,
      yaw: 90},
    "5":{
      x: 144,
      y: 57,
      yaw: 90},
  },
  "2":{
    "6":{
      x: 136,
      y: 457,
      yaw: 270},
    "7":{
      x: 138,
      y: 457,
      yaw: 270},
    "8":{
      x: 140,
      y: 457,
      yaw: 270},
    "9":{
      x: 142,
      y: 457,
      yaw: 270},
    "10":{
      x: 144,
      y: 457,
      yaw: 270},
  },
}
