# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}

# 4 drones
{
  "1":{
    "1":{
      x: 0,
      y: 0,
      yaw: 90},
    "2":{
      x: 2,
      y: 0,
      yaw: 90},
  },
  "2":{
    "3":{
      x: 0,
      y: 5,
      yaw: 270},
    "4":{
      x: 2,
      y: 5,
      yaw: 270},
  },
}

# 10 drones
# {
#   "1":{
#     "1":{
#       x: 0,
#       y: 0,
#       yaw: 90},
#     "2":{
#       x: 2,
#       y: 0,
#       yaw: 90},
#     "3":{
#       x: 4,
#       y: 0,
#       yaw: 90},
#     "4":{
#       x: 6,
#       y: 0,
#       yaw: 90},
#     "5":{
#       x: 8,
#       y: 0,
#       yaw: 90},
#   },
#   "2":{
#     "6":{
#       x: 0,
#       y: 5,
#       yaw: 270},
#     "7":{
#       x: 2,
#       y: 5,
#       yaw: 270},
#     "8":{
#       x: 4,
#       y: 5,
#       yaw: 270},
#     "9":{
#       x: 6,
#       y: 5,
#       yaw: 270},
#     "10":{
#       x: 8,
#       y: 5,
#       yaw: 270},
#   },
# }
