# Drone spawn positions
# Format: team_id:{drone_id:{x, y, yaw}, ...}
{
  "1":{
    "1":{
      x: 110,
      y: 46,
      yaw: 90},
    "2":{
      x: 112,
      y: 46,
      yaw: 90},
    "3":{
      x: 114,
      y: 46,
      yaw: 90},
    "4":{
      x: 116,
      y: 46,
      yaw: 90},
    "5":{
      x: 118,
      y: 46,
      yaw: 90},
  },
  "2":{
    "6":{
      x: 96,
      y: 440,
      yaw: 270},
    "7":{
      x: 98,
      y: 440,
      yaw: 270},
    "8":{
      x: 100,
      y: 440,
      yaw: 270},
    "9":{
      x: 102,
      y: 440,
      yaw: 270},
    "10":{
      x: 104,
      y: 440,
      yaw: 270},
  },
}
